[admin]
port = "1432"
database = "admin"
# 微信 以下appid,appsecret为测试号，使用时请替换为你自己信息
#[admin.wechat]
#appurl = "127.0.0.1:8888"
#appid = "your appId"
#appsecret = "your appSecret"
#token = "go_jwt"
#encodingaeskey = "your encodingaeskey"
#jwt
#[admin.jwt]
#secrets = "secret"
#token_expire = 1
#token_name = "Authorization"